add jdbc
vr242kj/Library pull request #4
Opened 2023-03-30 20:13 UTC by vr242kj

2023-03-31 13:43 UTC, vladyslavnovak requested changes
Пока что прокомментировал то что заметил, исправь эти моменты и после этого еще раз пройдусь. Если что то не понятно. нужны доп. разяснения или ссылки на материалы - спрашивай.

2023-03-31 13:43 UTC, vladyslavnovak commented on src/dao/BookDaoImplementation.java
> +                books.add(new Book(rs.getInt("id"), rs.getString("name"), rs.getString("author"), rs.getInt("readerId")));
У тебя повторяется операция маппинга из rs в книгу несколько раз, предлагаю вынести эту операцию в отдельный метод

2023-03-31 13:43 UTC, vladyslavnovak commented on src/dao/BookDaoImplementation.java
> +        }
Предлагаю переработать обработку исключений.
1. Exception - это общий тип, нужно сузить, так для разных типов исключений может быть разная логика их обработки. В данном случае у тебя может выброситься SQLException;
2. Сделай кастомное сообщение об ошибке для пользователя, чтоб он мог понять что именно случилось и какие есть дальнейшие варианты действия для него;
3. Это касается всей программы, не только этого места

2023-03-31 13:43 UTC, vladyslavnovak commented on src/dao/BookDaoImplementation.java
> +            rs = statement.executeQuery(query);
В этом месте(и в подобных далее) следует использовать вместо String.format PreparedStatement

2023-03-31 13:43 UTC, vladyslavnovak commented on src/dao/BookDaoImplementation.java
> +        return Optional.empty();
После каждого обращения к БД нужно закрывать connection, это касается не только этого места. Предлагаю использовать в этих целях конструкцию  try-with-resources

2023-03-31 13:43 UTC, vladyslavnovak commented on src/dao/BookDaoImplementation.java
> +            System.out.println("Row Inserted");
Зачем этот вывод? Какой он предоставляет смысл для пользователя? Как по мне, такая информация скорее должна выводится в лог, а пользователю в UI слое сообщить об успешности/не успешности операции.

2023-03-31 13:43 UTC, vladyslavnovak commented on src/dao/BookDaoImplementation.java
> +        return bookToSave;
Здесь должна возвращатся книга с назначеным id, иначе нет смысла возвращать с метода тот самый обьект что был на входе. Это касается и других подобных методов.

2023-03-31 13:43 UTC, vladyslavnovak commented on src/dao/ReaderDaoImplementation.java
> +    ResultSet rs;
Здесь замечания все те же что и в BookDaoImplementation, предлагаю убрать все эти переменные с уровня класса в методы, где они будут создаватся по мере вызова того или иного метода.

2023-03-31 13:43 UTC, vladyslavnovak commented on schema.sql
> +                       name VARCHAR(25) NOT NULL
Незначительное замечание, но я бы увеличил ограничение по длине имени хотя бы в два раза, имена разные могут быть

2023-03-31 13:43 UTC, vladyslavnovak commented on src/dao/ConnectionUtil.java
> +                System.out.println("Connection Failed");
В этом месте стоит также завершить программу, так как без connectiona к БД с нее пользы нет, а сообщение об критической ошибке как эта, лучше выводить через System.err

2023-03-31 13:43 UTC, vladyslavnovak commented on src/main/java/ui/UserInterface.java
> -
Предлагаю убрать static, он здесь не нужен

2023-03-31 13:43 UTC, vladyslavnovak commented on src/dao/ConnectionUtil.java
> +    public Connection connectionToDatabase (String dbname, String user, String pass) {
название БД, имя пользователя и пароль лучше перенести в файл application.properties и подтягивать оттуда

2023-03-31 13:43 UTC, vladyslavnovak commented on src/dao/BookDaoImplementation.java
> +
зачем выносить эти переменные на уровень класса? я бы так не делал, а создавал в каждом методе отдельно. по мере его вызовов

2023-03-31 13:43 UTC, vladyslavnovak commented on src/main/java/service/LibraryService.java
> -    public Optional<Reader> currentReaderOfBook(String bookId) throws IllegalArgumentException {
В сигнатуре метода обявлять unchecked exception не надо, в общем углубись в тему исключений

2023-03-31 13:43 UTC, vladyslavnovak commented on src/main/java/Main.java
> -public class Main {
Нужно навести порядок в структуре папок. С текущей структурой у меня даже не запускается проект.

2023-03-31 13:43 UTC, vladyslavnovak commented on src/main/java/service/LibraryService.java
> -            throw new IllegalArgumentException(JUST_NUMBER);
Исключение выбрасывается и насколько я понимаю, так как не удается запустить програму из за замеса в структуре проекта, на этом программа завершается. Это не совсем правильно, так как неправильный ввод - это не на столько критическая ошибка, чтоб останавливать програму. Исключение нужно отловить и настроить логику его обработки. Данный принцип нужно применить к всем остальным исключениям. Нужно провести разграничение между исключениями критическими, после которых программа останавливается и исключениями при которых можно продолжать работу.

2023-04-02 09:53 UTC, vr242kj commented on src/dao/BookDaoImplementation.java
> +                books.add(new Book(rs.getInt("id"), rs.getString("name"), rs.getString("author"), rs.getInt("readerId")));
создал отдельный метод createBookFromDB

2023-04-02 10:01 UTC, vr242kj commented on src/dao/BookDaoImplementation.java
> +        }
я поменял в классе где подключение к бд все Exception на SQLException. В остальных случаях есть кастомное сообщение об ошибке для пользователя.

2023-04-02 10:01 UTC, vr242kj commented on src/dao/BookDaoImplementation.java
> +            rs = statement.executeQuery(query);
done.

2023-04-02 10:01 UTC, vr242kj commented on src/dao/BookDaoImplementation.java
> +        return Optional.empty();
done.

2023-04-02 10:02 UTC, vr242kj commented on src/dao/BookDaoImplementation.java
> +            System.out.println("Row Inserted");
вывод убрал, сообщение еще не добавил

2023-04-02 10:03 UTC, vr242kj commented on src/dao/BookDaoImplementation.java
> +        return bookToSave;
done

2023-04-02 10:03 UTC, vr242kj commented on src/dao/ReaderDaoImplementation.java
> +    ResultSet rs;
убрал

2023-04-02 10:03 UTC, vr242kj commented on schema.sql
> +                       name VARCHAR(25) NOT NULL
done

2023-04-02 10:04 UTC, vr242kj commented on src/dao/ConnectionUtil.java
> +                System.out.println("Connection Failed");
убрал эту проверку

2023-04-02 10:04 UTC, vr242kj commented on src/main/java/ui/UserInterface.java
> -
done

2023-04-02 10:07 UTC, vr242kj commented on src/dao/ConnectionUtil.java
> +    public Connection connectionToDatabase (String dbname, String user, String pass) {
готово

2023-04-02 10:08 UTC, vr242kj commented on src/dao/BookDaoImplementation.java
> +
удалил переменный из класса и создаю их  в каждом методе отдельно

2023-04-02 10:09 UTC, vr242kj commented on src/main/java/service/LibraryService.java
> -    public Optional<Reader> currentReaderOfBook(String bookId) throws IllegalArgumentException {
там есть перехват exception, вывод для пользователя тоже

2023-04-02 10:09 UTC, vr242kj commented on src/main/java/Main.java
> -public class Main {
вроде сделал

2023-04-02 11:06 UTC, vladyslavnovak reviewed
Многие замечания касаются не только конкретного места, где они оставлены, но и других подобных мест в коде.

2023-04-02 11:06 UTC, vladyslavnovak commented on src/main/java/dao/BookDaoImplementation.java
> +    String URL = "jdbc:postgresql://localhost:5432/library";
Подключение к БД нужно полностью инкапсулировать в отдельном классе, ознакомся с принципами SOLID, в этом случае имею ввиду single resposibility  principle.
URL в свою очередь нужно вынести в пропертис и оттуда подтягивать.

2023-04-02 11:06 UTC, vladyslavnovak commented on src/main/java/dao/BookDaoImplementation.java
> +        try (Connection con = DriverManager.getConnection(URL, connectionUtil.propertiesForConnection());
Это все нужно инкапсулировать в классе коннекшина, в котом будет метод который возвращает готовый коннекшн, а это все DriverManager.getConnection... будет производится у него под капотом.

2023-04-02 11:06 UTC, vladyslavnovak commented on src/main/java/dao/BookDaoImplementation.java
> +        String sql = "select * from book";
этот обьект ты используешь только раз, нет смысла его выносить в отдельную переменную

2023-04-02 11:06 UTC, vladyslavnovak commented on src/main/java/dao/BookDaoImplementation.java
> +            System.out.println(e);
Сейчас ты выводишь на экран само исключение в его строковом представлении. Такое сообщение обычному пользователю, не разработчику, не обяснит из за чего произошла ошибка и как ее можно решить. Нужно переделать.

2023-04-02 11:06 UTC, vladyslavnovak commented on src/main/java/dao/BookDaoImplementation.java
> +             PreparedStatement ps = con.prepareStatement(sql)) {
PreparedStatement не нужно помещать в try-w/-resources

2023-04-02 11:06 UTC, vladyslavnovak commented on src/main/java/dao/BookDaoImplementation.java
> +    private Book createBookFromDB (ResultSet rs) throws SQLException {
название метода нужно подкорректировать, так как здесь ты именно мапиш, а не создаешь, например на bookMapper

2023-04-02 11:06 UTC, vladyslavnovak commented on src/main/java/dao/BookDaoImplementation.java
> +            bookToSaveId = ps.executeUpdate();
здесь не верно, PreparedStatement.executeUpdate() не возвращает id новодобавленной записи, погугли

2023-04-02 11:06 UTC, vladyslavnovak commented on src/main/java/dao/BookDaoImplementation.java
> +    public Optional<Book> save (Book bookToSave) {
Почему ты здесь возвращаешь опшионал? Суть опшионала - это некий контейнер(который сам по себе является обьектом) в котором обьект может быть, а может не быть. Это полезно когда ты например хочешь вытащить запись с БД с каким то айди - она может сущетсвовать, а может не существовать. В данном случае у тебя книга 100% есть, но пока что без айди,  ты ведь передаешь ее в качестве аргумента. А вот результатом работы метода должна быть книга, которая уже имеет айдишник присвоеный базой данных.

2023-04-02 11:06 UTC, vladyslavnovak commented on src/main/java/dao/BookDaoImplementation.java
> +        return 0;
Предлагаю перейти на использование обьектов, а не примитивов, т. е. Integer, Long... вместо int, long. Тогда можно будет вместо условного 0, использовать null.

2023-04-02 11:06 UTC, vladyslavnovak commented on src/main/java/dao/ConnectionUtil.java
> +    public Properties loadPropertiesFile() throws Exception {
нужно сузить тип исключения и добавить логику его обработки. Я бы использовал здесь try-with-resources

2023-04-02 11:06 UTC, vladyslavnovak commented on src/main/java/dao/ConnectionUtil.java
> +    public Properties propertiesForConnection () {
Этот метод не должен быть паблик, так как вся логика подключения к БД должна быть инкапсулирована в этом классе

2023-04-02 11:06 UTC, vladyslavnovak commented on src/main/java/ui/UserInterface.java
>                      case "EXIT" -> exitFromProgram();
здесь было бы неплохо сделать ignore case

2023-04-02 11:06 UTC, vladyslavnovak commented on src/main/java/ui/UserInterface.java
>                  System.err.println(e);
Разве неправильный ввод это такая критическая ошибка чтоб выводить ее через System.err? Переделай на System.out + пользователю не надо выводить java.lang.IllegalArgumentException: - он не разработчик, ему эта инфа не к чему.

2023-04-02 11:09 UTC, vladyslavnovak commented on src/dao/BookDaoImplementation.java
> +        return bookToSave;
здесь еще нужно поработать, см. последний коммент

2023-04-02 11:10 UTC, vladyslavnovak commented on src/dao/ConnectionUtil.java
> +                System.out.println("Connection Failed");
Проверка правильная, не нужно ее убирать, только добавить после сообщения еще system.exit

2023-04-02 11:11 UTC, vladyslavnovak commented on src/dao/ConnectionUtil.java
> +    public Connection connectionToDatabase (String dbname, String user, String pass) {
Хорошо, но над классом подключения к БД надо еще поработать, см. новые комменты.

2023-04-02 11:11 UTC, vladyslavnovak commented on src/dao/BookDaoImplementation.java
> +
Список книг тоже надо убрать из классовых переменных

2023-04-02 14:42 UTC, singeev commented on src/main/java/dao/BookDaoImplementation.java
> +             PreparedStatement ps = con.prepareStatement(sql)) {
Нужно закрывать все 3 объекта:
* connection
* preparedStatement
* resultSet
Тут моя вина, Влад, я в твоем коде это не доглядел.

Почитайте вот тут:
* https://docs.oracle.com/javadb/10.8.3.0/devguide/cdevconcepts839085.html
* https://stackoverflow.com/questions/4507440/must-jdbc-resultsets-and-statements-be-closed-separately-although-the-connection

Оптимально - открывать все 3 объекта внутри `try` и все. Они все будут закрыты автоматически за счет `try-with-resources`

2023-04-02 15:26 UTC, vladyslavnovak commented on src/main/java/dao/BookDaoImplementation.java
> +             PreparedStatement ps = con.prepareStatement(sql)) {
Ну я тоже должен был бы обратить на это внимание. Я так понимаю обьект определяется как ресурс, если его класс имплементирует Closeable or AutoCloseable?

2023-04-03 22:39 UTC, vr242kj commented on src/main/java/dao/BookDaoImplementation.java
> +    public Optional<Book> save (Book bookToSave) {
можно тогда написать метод findByName, который ищет в бд книгу по имени и возвращает книгу с id? 
return в методе save буде вызывать findByName.

2023-04-04 08:53 UTC, vladyslavnovak commented on src/main/java/dao/BookDaoImplementation.java
> +    public Optional<Book> save (Book bookToSave) {
Если так сделать, то что будет если у тебя в библиотеке будет несколько одинаковых книг с одинаковыми именами? Например несколько экземпляров одной и той же книги.

2023-04-04 16:53 UTC, vr242kj commented on src/dao/BookDaoImplementation.java
> +            rs = statement.executeQuery(query);
теперь использую PreparedStatement

2023-04-04 16:54 UTC, vr242kj commented on src/dao/BookDaoImplementation.java
> +        return bookToSave;
решил с помощью statement.getGeneratedKeys()

2023-04-04 16:54 UTC, vr242kj commented on src/dao/ConnectionUtil.java
> +                System.out.println("Connection Failed");
немного по другому сделал

2023-04-04 16:54 UTC, vr242kj commented on src/dao/ConnectionUtil.java
> +    public Connection connectionToDatabase (String dbname, String user, String pass) {
класс подключения инкапсулировал

2023-04-04 16:55 UTC, vr242kj commented on src/dao/BookDaoImplementation.java
> +
убрал

2023-04-04 16:56 UTC, vr242kj commented on src/main/java/service/LibraryService.java
> -            throw new IllegalArgumentException(JUST_NUMBER);
добавил свой exception, и его перехват

2023-04-04 16:56 UTC, vr242kj commented on src/main/java/dao/BookDaoImplementation.java
> +    String URL = "jdbc:postgresql://localhost:5432/library";
переделал

2023-04-04 16:56 UTC, vr242kj commented on src/main/java/dao/BookDaoImplementation.java
> +        try (Connection con = DriverManager.getConnection(URL, connectionUtil.propertiesForConnection());
инкапсулировал

2023-04-04 16:56 UTC, vr242kj commented on src/main/java/dao/BookDaoImplementation.java
> +        String sql = "select * from book";
переделал

2023-04-04 16:57 UTC, vr242kj commented on src/main/java/dao/BookDaoImplementation.java
> +            System.out.println(e);
добавил свой exception и написал сообщение для пользователя.

2023-04-04 16:58 UTC, vr242kj commented on src/main/java/dao/BookDaoImplementation.java
> +    private Book createBookFromDB (ResultSet rs) throws SQLException {
готово

2023-04-04 16:58 UTC, vr242kj commented on src/main/java/dao/BookDaoImplementation.java
> +            bookToSaveId = ps.executeUpdate();
переделал на bookToSave.setId(generatedKeys.getInt(1))

2023-04-04 16:59 UTC, vr242kj commented on src/main/java/dao/BookDaoImplementation.java
> +    public Optional<Book> save (Book bookToSave) {
переделал на с помощью statement.getGeneratedKeys()

2023-04-04 17:00 UTC, vr242kj commented on src/main/java/dao/BookDaoImplementation.java
> +        return 0;
сделал

2023-04-04 17:01 UTC, vr242kj commented on src/main/java/dao/ConnectionUtil.java
> +    public Properties loadPropertiesFile() throws Exception {
сузил и добавил try-with-resources

2023-04-04 17:01 UTC, vr242kj commented on src/main/java/dao/ConnectionUtil.java
> +    public Properties propertiesForConnection () {
поменял на private

2023-04-04 17:02 UTC, vr242kj commented on src/main/java/ui/UserInterface.java
>                      case "EXIT" -> exitFromProgram();
добавил

2023-04-04 17:02 UTC, vr242kj commented on src/main/java/ui/UserInterface.java
>                  System.err.println(e);
вроде сделал

2023-04-05 08:42 UTC, vladyslavnovak reviewed
Оставил некоторые комментарии по коду. Как раньше многие из них оставлены в одном месте, но ошибка повторяется еще и в других местах.
Так же попробовал запустить приложение и оно не верно работает, ты его тестировал сам?
Вот некоторые из моих вводов(вывод менюшки удалил для сокращения текста):
5
Please enter new book id and reader id separated by "/". Like this: book id / reader id
1/12321 **здесь разве не нумерик ввод? касается практически всех примеров ниже**
Book ID and Reade ID must be numeric
____________
5
Please enter new book id and reader id separated by "/". Like this: book id / reader id
123123/1
Book ID and Reade ID must be numeric
_____________
5
Please enter new book id and reader id separated by "/". Like this: book id / reader id
asdfasdfa/1
Book ID and Reade ID must be numeric
______________
1
Book{id = 1, name = 'In Search of Lost Time', author = 'Marcel Proust', readerId = 0}
Book{id = 2, name = 'Ulysses', author = 'James Joyce', readerId = 0}
Book{id = 3, name = 'Don Quixote', author = 'Miguel de Cervantes', readerId = 0}

//
///
///

2
Reader{id = 1, name = Gabriel Garcia Marquez}
Reader{id = 2, name = F. Scott Fitzgerald}
Reader{id = 3, name = Herman Melville}

//
///
///
5
Please enter new book id and reader id separated by "/". Like this: book id / reader id
1/1 
Book ID and Reade ID must be numeric

2023-04-05 08:42 UTC, vladyslavnovak commented on src/main/java/dao/BookDaoImplementation.java
> +            statement.setNull(1, Types.INTEGER);
Здесь нулл можно не сетить, а сразу прописать в запросе. У тебя ведь меняется только айдишник

2023-04-05 08:42 UTC, vladyslavnovak commented on src/main/java/dao/BookDaoImplementation.java
> +            try(var generatedKeys =  statement.getGeneratedKeys()) {
Из описания метода getGenerated: If this Statement object did not generate any keys, an empty ResultSet object is returned. Надо обработать сценарий когда не запишется книга. Сейчас же у тебя вернется стартовая книга без какого либо признака ошибки.

2023-04-05 08:42 UTC, vladyslavnovak commented on src/main/java/dao/BookDaoImplementation.java
> +public class BookDaoImplementation implements DaoBookInterface {
Наведи порядок в наименованиях твоих ДАО имплементаций, чтоб сходу было понятно где какая. Я бы вообще удалил реализацию через список

2023-04-05 08:42 UTC, vladyslavnovak commented on src/main/java/service/LibraryService.java
Здесь можно было бы задать тип поля через интерфейс

2023-04-05 08:42 UTC, vladyslavnovak commented on src/main/java/service/LibraryService.java
С сервис слоя не надо возвращать опшионал. Здесь у тебя происходит бизнес логика и в слой презентаций нужно передать готовый результат. Опшионал это скорее промежуточный результат.

2023-04-05 08:42 UTC, vladyslavnovak commented on src/main/java/service/LibraryService.java
Эту проверку впринципе можно убрать, так как при неправильном вводе у тебя вылетит исключение ниже в Integer.parseInt().

2023-04-05 08:42 UTC, vladyslavnovak commented on src/main/java/service/ServiceException.java
> +}
Мне не совсем нравится эта история с одним исключением на все случаи жизни, как по мне нужно сделать несколько штук, каждое для своего сценария. Но здесь нужен комментарий Алекса.

2023-04-05 08:42 UTC, vladyslavnovak commented on src/main/java/ui/UserInterface.java
>          while (true) {
"WELCOME TO THE LIBRARY!" - используется только раз, я бы не выносил в отдельную переменную

2023-04-05 19:24 UTC, vr242kj commented on src/main/java/service/ServiceException.java
> +}
Ждём-с

2023-04-05 19:25 UTC, vr242kj commented on src/main/java/service/LibraryService.java
проверку убрал, добавил try-catch для Integer.parseInt()

2023-04-05 19:27 UTC, vr242kj commented on src/main/java/service/LibraryService.java
переделал, теперь возвращает либо объект либо null

2023-04-05 19:27 UTC, vr242kj commented on src/main/java/service/LibraryService.java
у меня 2 интерфейс, создаются в одном месте, переделал

2023-04-05 19:28 UTC, vr242kj commented on src/main/java/dao/BookDaoImplementation.java
> +public class BookDaoImplementation implements DaoBookInterface {
удалил реализацию через список, улучшил названия классов

2023-04-05 19:28 UTC, vr242kj commented on src/main/java/dao/BookDaoImplementation.java
> +            try(var generatedKeys =  statement.getGeneratedKeys()) {
сценарий обработал

2023-04-05 19:29 UTC, vr242kj commented on src/main/java/dao/BookDaoImplementation.java
> +            statement.setNull(1, Types.INTEGER);
прописал в запросе

2023-04-05 19:32 UTC, vr242kj commented on src/main/java/ui/UserInterface.java
>          while (true) {
я удалил все переменные типа String, теперь где они нужны стразу текст

2023-04-06 10:04 UTC, ahonsu commented on src/main/java/service/ServiceException.java
> +}
Поглядел код на тему исключений.

Общий подход к созданию разных типов исключений основан на том - а собирается ли разработчик по разному эти исключения обрабатывать? Если написано 25 типов исключений, но все они обрабатываются одинаково, например
```
} catch (Exception e){
                System.out.println(e.getMessage());
}
```
- тогда нет никакого смысла создать эти 25 разных типов.
Если же каждый тип ведет к разным сценариям, разным ответам пользователю, разным действиям в БД и т.п. - тогда каждый новый тип имеет свое предназначение.

В данном проекте, на мой взгляд, достаточно иметь эти 3 типа `ServiceException | DAOException | UserInputException` на данный момент. Если позже будут появляется другие/новые сценарии обработки ошибок - можно будет добавить и новые типы исключений.

2023-04-07 16:58 UTC, vladyslavnovak commented on src/main/java/ui/UserInterface.java
>          while (true) {
Все не надо. Если обьект используется у тебя больше раза - его стоит вынести в переменную и через нее к нему обращаться.

2023-04-07 18:00 UTC, vladyslavnovak reviewed
Добавь единого стиля в сообщениях для пользователя. Например когда одалживаешь книгу у тебя никакого сообщения об успешной операции нет, но вот когда возвращаешь - выводишь сообщение Book return successful.
Программу нужно еще тестировать и закрывать дыры как эта:
TYPE “EXIT” TO STOP THE PROGRAM AND EXIT!
8
Write book id:
2
Exception in thread "main" java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at service.LibraryService.currentReaderOfBook(LibraryService.java:34)
	at ui.UserInterface.printCurrentReaderOfBookByReaderId(UserInterface.java:101)
	at ui.UserInterface.printMenu(UserInterface.java:43)
	at Main.main(Main.java:7)

Process finished with exit code 1
_______________________________________________

Как по мне,  текст об ошибке мало информативный, нужно доработать.
4
Please enter new book name and author separated by "/". Like this: name/author
12123123////author
Try again like this: name/author, without spaces between slash. Author must be literal

2023-04-07 18:00 UTC, vladyslavnovak commented on src/main/java/service/LibraryService.java
> +        if (!inputBookIDAndReaderID.matches("^\\s*\\w+\\/(\\w+\\s*)$")) {
Почему ты здесь согласен принимать буквы? Ты ведь ожидаешь от пользователя чтоб он ввел айдишники. Если в этом месте валидировать на цифры, то дальше переменные bookID and readerID можно инициализировать вне блока трай.

2023-04-08 19:19 UTC, vr242kj commented on src/main/java/service/LibraryService.java
> +        if (!inputBookIDAndReaderID.matches("^\\s*\\w+\\/(\\w+\\s*)$")) {
да, ты прав, лучше переписать проверку в regex.

2023-04-09 16:47 UTC, singeev commented on data.sql
> +                                   ('Don Quixote', 'Miguel de Cervantes');
Этот файл должен быть в `src/main/resources`

2023-04-09 16:47 UTC, singeev commented on schema.sql
> +);
Этот файл должен быть в `src/main/resources`

2023-04-09 16:47 UTC, singeev commented on src/main/java/dao/ConnectionUtil.java
> +    }
Пару предложений:
1. Не вижу смысла читать файл пропертей при создании каждого коннекта к БД. Есть смысл прочитать его один раз при старте приложения и все, потом переиспользовать полученные проперти.
2. Если не удалось прочитать файл, ты просто пишешь лог сообщение. А по факту, программа работать не сможет вообще. Рекомендую в случае неудачи полностью остановить программу.

2023-04-09 16:47 UTC, singeev commented on src/main/java/dao/DaoBookImplementation.java
>      }
1. Название метода должно содержать глагол. Например, подходящим названием для этого метода-маппера было бы `mapToBook(ResultSet rs)`
2. Когда ты достаешь значения из резалтСета - могут выскакивать исключения. Ты их обрабатываешь на уровне выше - в методе ДАО и пишешь в логи что-то вроде "Database error during retrieval of..." - т.е. все верно, но можно было бы код в методе-маппере окружить своим try-catch и писать в логи более точное сообщение `"Failed to map resultSet to Book object: " + e` например. Это упростит поиск ошибок в дальнейшем.

2023-04-09 16:47 UTC, singeev commented on src/main/java/dao/DaoBookImplementation.java
>      }
Давай переделаем этот кусок логики.
Ты написал этот метод ради единственного сценария - в итоге тебе нужно получить объект читателя по айди книги, которую он читает.
И ты делаешь это за 2 шага:
1. Получаешь айди читателя по айди книги
2. Получаешь объект читателя по его айди

Нужно сделать это одним методом в ReaderDao. Что-то вроде `Reader findByBookId(long bookId)`

2023-04-09 16:47 UTC, singeev commented on src/main/java/dao/DaoBookInterface.java
> +    Integer findReaderIdByBookId (int bookId);
В чем причина замены `long` на `int`?

2023-04-09 16:47 UTC, singeev commented on src/main/java/dao/DaoReaderImplementation.java
>      }
Такие же мысли, как и про маппер в ДАО книг

2023-04-09 16:47 UTC, singeev commented on src/main/java/service/LibraryService.java
> +       int bookID;
Плохая практика - давать такие имена: `bookId` и `bookID`. Чтобы отделить 2 различных типа, чаще делают более явные имена: `bookIdString` и `bookIdNumeric` или `bookIdInt`

2023-04-09 16:47 UTC, singeev commented on src/main/java/service/LibraryService.java
> +        return daoReaderImplementation.findById(readerID).orElse(null);
Про это уже написал выше - лучше сделать это за одно действие (один запрос в БД) в ДАО читателей.

2023-04-09 16:47 UTC, singeev commented on src/main/java/service/LibraryService.java
> +        }
Подумай, как избавится от повторений? Ты пишешь одно и то же раз за разом.

2023-04-09 16:47 UTC, singeev commented on src/main/java/ui/UserInterface.java
>          }
Если бы ты вернул из сервиса тип `Optional<Reader>` - ты мог бы тут написать:
```
private void printCurrentReaderOfBookByReaderId () {
        System.out.println("Write book id:");
        String bookId = input.nextLine();
        libraryService.currentReaderOfBook(bookId.trim())
            .ifPresentOrElse(
                System.out::println,
                () -> System.out.println("This book is in the library.")
            );
    }
```
Старайся по возможности использовать Optional, если он у тебя уже где-то есть.

2023-04-12 21:09 UTC, vr242kj commented on src/main/java/service/LibraryService.java
> +        }
создал отдельный метод для конвертации

2023-04-12 21:11 UTC, vr242kj commented on src/main/java/dao/DaoBookInterface.java
> +    Integer findReaderIdByBookId (int bookId);
после удаления AtomicLong, подумал что можно перейти на int

2023-04-16 13:09 UTC, singeev commented on src/main/java/service/LibraryService.java
@vladyslavnovak я тут не согласен.
Нет такого разделения, куда принятно возвращать опшнл, куда не принято.
Общий принцип - если метод (в любом классе) может вернуть нулл - лучше заменить возвращаемый тип на опшнл. Это применимо и к ДАО методам, и к сервисным, и между компонентами... 

Вот тут я писал противоположный (твоему мнению) коммент: https://github.com/vr242kj/Library/pull/4#discussion_r1161312445

2023-04-16 13:18 UTC, vladyslavnovak commented on src/main/java/service/LibraryService.java
@singeev согласен, какую то отсебятину выдал(

2023-04-17 18:50 UTC, singeev commented on src/main/java/dao/DaoBookInterface.java
> +    Integer findReaderIdByBookId (int bookId);
В целом да, но когда у тебя объекты хранятся в БД и айди тоже генерируется в БД - общепринятая практика использовать тип `long` для айди.

2023-04-17 19:11 UTC, ahonsu commented on src/main/java/dao/DaoBookImplementation.java
> +                }
Твой запрос в БД подразумевает, что ты должен получить одну книгу (или ни одной). Поэтому в таких случаях вместо бесконечного цикла `while` используют просто `if(resultSet.next())`.

Погляди остальные методы в ДАО классах, это есть не только тут.

2023-04-17 19:11 UTC, ahonsu commented on src/main/java/dao/DaoBookImplementation.java
>      }
Ты создаешь лишнюю зависимость: новый ДАО объект, ради того, чтобы вытащить читателя по его айди. При этом у тебя есть SQL запрос с джойном, который уже вытаскивает из БД этого читателя (за исключением имени).
Оптимально будет просто добавить в твой select нужные колонки и прямо тут собрать объект читателя, не создавая дополнительные ДАО классы.

2023-04-17 19:11 UTC, singeev commented on src/main/java/dao/DaoReaderImplementation.java
> +public class DaoReaderImplementation implements DaoReaderInterface {
По поводу имени класса.
Общепринятые правила такие:
* название сущности (читатель, книга...)
* тип компонента (сервис, дао...)
* далее идет вариант имплементации (если класс имплементит интерфейс) - JdbcImpl, FileImpl, InMemoryImpl...
Т.е. в этом случае подходящим названием класса было бы `ReaderDaoJdbcImpl`. Для читателей такой же подход.

2023-04-17 19:11 UTC, singeev commented on src/main/java/dao/DaoReaderImplementation.java
>      }
Два замечения:
1. Снова лишний раз создаешь дополнительный ДАО объект. Можно собрать нужный объект из того же `resultSet` если дополнить SQL запрос нужными колонками. Общий принцип в таких случаях - избегать лишних обращений к БД. 
2. Структура данных Map подразумевает уникальные ключи. Значения у тебя сделаны типом `Optional<Book>`. Если возникнет ситуация, когда один читатель взял в библиотеке сразу несколько книг (что вполне возможно), твоя структура данных не сможет корректно вместить все данные. Подумай над альтернативным решением.

2023-04-17 19:11 UTC, singeev commented on src/main/java/dao/DaoReaderImplementation.java
> +            DaoBookImplementation daoBookImplementation = new DaoBookImplementation();
Когда SQL запросы становятся длиннее нескольких слов - есть смысл форматировать их и выносить в отдельную переменную. Так проще их читать и редактировать.

```suggestion
    public Map<Reader, Optional<Book>> findAllWithBooks () {
       var query = """
           select 
               reader.id, 
               reader.name, 
               book.id 
            from reader 
               inner join book on reader.id = book.readerid 
            order by reader.id
         """;
        try (var connection = ConnectionUtil.createConnection();
             var statement = connection.prepareStatement(query)) {
            Map<Reader, Optional<Book>> map = new HashMap<>();
```

2023-04-17 19:11 UTC, singeev commented on src/main/java/ui/UserInterface.java
> +    }
Обращай внимание на возможности `Optional` и, по возможности, используй!
На это обращают внимание, когда смотрят код потенциального джуна. Нужно чтобы ни у кого не было сомнений, что ты знаешь современный синтаксис.

```suggestion
    private void printAllBooksWithReaders() {
        libraryService.findAllBooksWithReaders().forEach(
                (key, value) ->
                    value.ifPresentOrElse(
                        reader -> System.out.println(key + " : " + reader),
                        () -> System.out.println(key + " : available")
                    )
                );
    }
```

2023-04-19 07:12 UTC, vr242kj commented on src/main/java/dao/DaoBookImplementation.java
> +                }
поменял, и не только здесь

2023-04-19 07:13 UTC, vr242kj commented on src/main/java/dao/DaoBookImplementation.java
>      }
переделал

2023-04-19 07:13 UTC, vr242kj commented on src/main/java/dao/DaoReaderImplementation.java
> +public class DaoReaderImplementation implements DaoReaderInterface {
готово.

2023-04-19 07:14 UTC, vr242kj commented on src/main/java/dao/DaoReaderImplementation.java
>      }
переделал.
решил использовать Map<Reader, List<Book>>

2023-04-19 07:15 UTC, vr242kj commented on src/main/java/dao/DaoReaderImplementation.java
> +            DaoBookImplementation daoBookImplementation = new DaoBookImplementation();
в двух местах поменял.

2023-04-19 07:27 UTC, vr242kj commented on src/main/java/ui/UserInterface.java
> +    }
питался переделать, так как был уже похожий случай - https://github.com/vr242kj/Library/pull/4#discussion_r1161312445.
Но я делал (key, value) -> {}, то есть в этих фигурных скобках писал что хочу делать из значениями key, value.
Нужно было без них и все бы заработало. Типа (key, value) -> value.ifPresentOrElse().

2023-04-20 11:29 UTC, singeev commented on src/main/java/dao/BookDaoJdbcImpl.java
> +                            rs.getString("author"), rs.getInt("readerId"));
Суть этого кода: если в БД айди читателя равен 0, тогда вызываем конструктор без айди читателя. При этом, поле `readerId` в классе `Book` - типа `long`, т.е. по дефолту оно тоже == 0, без всяких конструкторов.
Вопрос: зачем тогда так усложнять, когда ты просто можешь всегда вызывать второй конструктор (в котором есть айди читателя)? - ты получишь точно такое же поведение и результат.

2023-04-20 11:29 UTC, singeev commented on src/main/java/dao/BookDaoJdbcImpl.java
>                  }
можно так
```
while (resultSet.next()) {
                    var readerName = resultSet.getString("readerName");
                    var reader = Optional.ofNullable(readerName)
                            .map(Reader::new);
                    map.put(mapToBook(resultSet), reader);
                }
```

2023-04-20 11:29 UTC, singeev commented on src/main/java/dao/BookDaoJdbcInterface.java
> +public interface BookDaoJdbcInterface {
В названии интерфейсов, наоборот, не добавляют детали имплементации. Он должен быть универсальным. Правильное название для этого интерфейса  - `BookDao`

2023-04-20 11:29 UTC, singeev commented on src/main/java/dao/ReaderDaoJdbcImpl.java
> +                    map.get(mapToReader(resultSet)).add(new Book(resultSet.getLong("bookId"), resultSet.getString("bookName"), resultSet.getString("bookAuthor")));
Для таких действий есть готовые методы в классе `Map`. Например `map.merge()`. Попробуй переписать этот код с использованием стандартных методов! И почитай про остальные метода класса `Map`! - это снова на тему знания коллекций.

2023-04-20 14:33 UTC, singeev commented on src/main/java/dao/ReaderDaoJdbcImpl.java
> +                    map.get(mapToReader(resultSet)).add(new Book(resultSet.getLong("bookId"), resultSet.getString("bookName"), resultSet.getString("bookAuthor")));
Все верно.

Обрати внимание на читаемость своего кода! Ты написал все корректно, но у тебя один метод вызывается внутри параметров другого метода, а внутри него еще один метод и так далее. Это сложно читать.

В реальной жизни никто не оценит твою попытку сделать код "в одну строку", лучше вынести что-то в переменную, отформатировать немного... пусть кода будет чуть больше, но он будет понятнее. Плюс именование переменных - тоже обрати на это внимание, они должны помогать понять код.

Вот мой вариант твоего кода:
```
while (resultSet.next()) {
                    var book = new Book(
                        resultSet.getLong("bookId"),
                        resultSet.getString("bookName"),
                        resultSet.getString("bookAuthor")
                    );
                    map.merge(
                        mapToReader(resultSet),
                        List.of(book),
                        (addedBooks, newBooks) -> Stream
                            .concat(addedBooks.stream(), newBooks.stream())
                            .toList()
                    );
                }
```
Т.е. все то же самое, но просто в другой записи.

2023-04-20 15:06 UTC, vr242kj commented on src/main/java/dao/ReaderDaoJdbcImpl.java
> +                    map.get(mapToReader(resultSet)).add(new Book(resultSet.getLong("bookId"), resultSet.getString("bookName"), resultSet.getString("bookAuthor")));
да, так намного лучше

2023-04-20 15:18 UTC, singeev approved these changes
Хорошая работа! Можно мержить!
@vladyslavnovak, спасибо большое за помощь! Твои комментарии помогли проделать основную работу и довести код до хорошего состояния!

2023-04-20 15:21 UTC, merged

2023-04-20 15:50 UTC, vr242kj commented
Спасибо за помощь, @vladyslavnovak !